### ISSUE TITLE
Support for python2.7

### ISSUE THREAD

**Issue by NicolayP** [adafruit/Adafruit_CircuitPython_ServoKit#15]
Hello,
In one of my ros projects, I want to use this library, however there is no support for python 2.7. Do you consider adding it in a near future?

**Comment by dhalbert** [comment]
Our libraries are written for CircuitPython or for CPython 3.x (using the adafruit-blinka library to simulate the CircuitPython native modules). We don't support 2.7, and won't be adding it, since it has reached end of life.
