### ISSUE TITLE
Problem with ServoKit in Nvidia Xavier NX board.

### ISSUE THREAD

**Issue by AK51** [adafruit/Adafruit_CircuitPython_ServoKit#23]
I am using Nvidia Xavier NX board with PCA9685. Not sure if ServoKit has updated the version? Or The Nvidia Xavier NX Jetpack 4.4 does not support ServoKit library anymore...
I followed this youtube and his code works.
https://youtu.be/JSlJ8NVVWfQ?list=PLGs0VKk2DiYw_Xx7c3M_9HMEcn9hPhFJV&t=2773
I just used the example code, but in the line kit=ServoKit(channels=16), it gives error said ModuleNotFoundError: No module named 'machine'.
The error starts from adafriut_servokit.py --> ..python3.6/site-packages/busio.py...
Thx.
![IMG_3853](https://user-images.githubusercontent.com/8468724/95608571-df6d1080-0a8f-11eb-8857-98c8e68490d6.JPG)

**Comment by ErickDiaz** [comment]
I'm getting the same issue, I have recently updated the libraries, I didn't have the issue before the update, I started a fresh new install of python in the jetson nano and had the issue again
```
Initializing Servos
Traceback (most recent call last):
  File "spotmicro_ai/jetson_nano/src/spotmicroai/initial_position.py", line 11, in <module>
    i2c_bus0=(busio.I2C(board.SCL_1, board.SDA_1))
  File "/home/balam/balam-env/lib/python3.6/site-packages/busio.py", line 31, in __init__
    self.init(scl, sda, frequency)
  File "/home/balam/balam-env/lib/python3.6/site-packages/busio.py", line 59, in init
    from machine import I2C as _I2C
ModuleNotFoundError: No module named 'machine'
Exiting... 
```

**Comment by Govind-pixel** [comment]
Hi All,
I am using Nvidia Jetson nano with PCA9685 I am also getting same error like you.Is there any fix available for this.

**Comment by ladyada** [comment]
@swarren has a fix coming
