### ISSUE TITLE
No Way to Reset PWM_hat.

### ISSUE THREAD

**Issue by delers447** [adafruit/Adafruit_CircuitPython_ServoKit#34]
Hello!  
I followed this tutorial off the adafruit webpage:  
https://cdn-learn.adafruit.com/downloads/pdf/adafruit-16-channel-pwm-servo-hat-for-raspberry-pi.pdf

I am making a robotic arm and after my code stops the pwm_hat is still broadcasting the PWM signal to the servos.  I am looking for a way to stop the signal.  
On page 17 of the linked documentation it says to substantiate the pwm object
> pwm = PWM(0x40)

 and then call the method setPWM().  I wanted to use the method
> pwm.setPWM(servo, 0, 0) 

to make the signal low on all ticks.  The issue is non of the libraries have the class PWM.  I even did 
> from PCA9865 import * 

and still nada.

Could this servo kit library give a way to reset the PWM Hat to stop broadcasting?

**Comment by tannewt** [comment]
The library reference of that PDF is incorrect. (This [Learn guide page](https://learn.adafruit.com/adafruit-16-channel-pwm-servo-hat-for-raspberry-pi/library-reference).)

Please stick to one support method while we sort out an issue. (Forum post here: https://forums.adafruit.com/viewtopic.php?f=60&t=186459 )
