### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools.command.build'

### ISSUE THREAD

**Issue by Real4LA** [adafruit/Adafruit_CircuitPython_ServoKit#45]
jetson@jetson:~$ pip3 install adafruit-circuitpython-servokit
Collecting adafruit-circuitpython-servokit
  Using cached https://files.pythonhosted.org/packages/a2/65/5da8d1d4a22701fedf9dbae9094e40185d58be25b86175  eb0861d55398a5/adafruit-circuitpython-servokit-1.3.10.tar.gz
Collecting Adafruit-Blinka>=7.0.0 (from adafruit-circuitpython-servokit)
Collecting adafruit-circuitpython-busdevice (from adafruit-circuitpython-servokit)
Collecting adafruit-circuitpython-register (from adafruit-circuitpython-servokit)
  Downloading https://files.pythonhosted.org/packages/ab/6f/538ef9e9f7ac5c045287e3894d59963a1723e4fde7321d8  7d6d521071cc2/adafruit-circuitpython-register-1.9.10.tar.gz
Collecting adafruit-circuitpython-pca9685 (from adafruit-circuitpython-servokit)
  Downloading https://files.pythonhosted.org/packages/0d/08/a2b02758b6467e43810cfefb654fabf0db94f53c035d3cd  75625d6206fd4/adafruit-circuitpython-pca9685-3.4.3.tar.gz
Collecting adafruit-circuitpython-motor (from adafruit-circuitpython-servokit)
  Downloading https://files.pythonhosted.org/packages/30/1a/36eb785a4e82ef3209eb4db0c1013d2509a6c65fbfca205  75b5b0f8343c8/adafruit-circuitpython-motor-3.4.2.tar.gz
Collecting Jetson.GPIO (from Adafruit-Blinka>=7.0.0->adafruit-circuitpython-servokit)
Collecting Adafruit-PlatformDetect>=3.13.0 (from Adafruit-Blinka>=7.0.0->adafruit-circuitpython-servokit)
Collecting adafruit-circuitpython-typing (from Adafruit-Blinka>=7.0.0->adafruit-circuitpython-servokit)
Collecting pyftdi>=0.40.0 (from Adafruit-Blinka>=7.0.0->adafruit-circuitpython-servokit)
  Using cached https://files.pythonhosted.org/packages/17/ce/a97811c3e7e2d5a9520b88801dcc70ac1b553ed31b9819  b2fce14ffa9aa3/pyftdi-0.54.0-py3-none-any.whl
Collecting Adafruit-PureIO>=1.1.7 (from Adafruit-Blinka>=7.0.0->adafruit-circuitpython-servokit)
Collecting typing-extensions; python_version <= "3.7" (from adafruit-circuitpython-typing->Adafruit-Blinka>  =7.0.0->adafruit-circuitpython-servokit)
  Using cached https://files.pythonhosted.org/packages/75/e1/932e06004039dd670c9d5e1df0cd606bf46e29a28e65d5  bb28e894ea29c9/typing_extensions-4.2.0-py3-none-any.whl
Collecting pyusb!=1.2.0,>=1.0.0 (from pyftdi>=0.40.0->Adafruit-Blinka>=7.0.0->adafruit-circuitpython-servok  it)
  Using cached https://files.pythonhosted.org/packages/15/a8/4982498b2ab44d1fcd5c49f07ea3795eab01601dc143b0  09d333fcace3b9/pyusb-1.2.1-py3-none-any.whl
Collecting pyserial>=3.0 (from pyftdi>=0.40.0->Adafruit-Blinka>=7.0.0->adafruit-circuitpython-servokit)
  Using cached https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826  266d186f96f558/pyserial-3.5-py2.py3-none-any.whl
Building wheels for collected packages: adafruit-circuitpython-servokit, adafruit-circuitpython-register, a  dafruit-circuitpython-pca9685, adafruit-circuitpython-motor
  Running setup.py bdist_wheel for adafruit-circuitpython-servokit ... done
  Stored in directory: /home/jetson/.cache/pip/wheels/9a/8a/58/e96be07e59cbfe89bfd5236fe7b81841501b429ee455  67a3a4
  Running setup.py bdist_wheel for adafruit-circuitpython-register ... done
  Stored in directory: /home/jetson/.cache/pip/wheels/11/d2/b6/8084921c4e523d6deb345cb81c2df1f3da09aa51e768  b41015
  Running setup.py bdist_wheel for adafruit-circuitpython-pca9685 ... done
  Stored in directory: /home/jetson/.cache/pip/wheels/0f/58/bc/f8c6af6a09410abba78f345858391a76cdc8962e1fd7  716f77
  Running setup.py bdist_wheel for adafruit-circuitpython-motor ... done
  Stored in directory: /home/jetson/.cache/pip/wheels/f7/95/0c/1e04540b0d61ba8b47cec19532256d936d530ccc12f9  17089f
Successfully built adafruit-circuitpython-servokit adafruit-circuitpython-register adafruit-circuitpython-p  ca9685 adafruit-circuitpython-motor
Installing collected packages: Jetson.GPIO, Adafruit-PlatformDetect, typing-extensions, adafruit-circuitpyt  hon-busdevice, adafruit-circuitpython-typing, pyusb, pyserial, pyftdi, Adafruit-PureIO, Adafruit-Blinka, ad  afruit-circuitpython-register, adafruit-circuitpython-pca9685, adafruit-circuitpython-motor, adafruit-circu  itpython-servokit
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/command/install.py", lin  e 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python3.7/distutils/command/install.py", line 390, in finalize_options
    ('build_lib', 'build_lib'))
  File "/usr/lib/python3.7/distutils/cmd.py", line 286, in set_undefined_options
    src_cmd_obj = self.distribution.get_command_obj(src_cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 857, in get_command_obj
    klass = self.get_command_class(command)
  File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/dist.py", line 634, in g  et_command_class
    self.cmdclass[command] = cmdclass = ep.load()
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line   2324, in load
    return self.resolve()
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line   2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'setuptools.command.build'

**Comment by ladyada** [comment]
try https://stackoverflow.com/questions/14426491/python-3-importerror-no-module-named-setuptools

**Comment by ladyada** [comment]
please check the jetson support forums for help, we know others have gotten it working - we do not own a jetson
