### ISSUE TITLE
"ValueError: SCL in use" occur when using Adafruit PCA9685 16-Channel Servo Driver

### ISSUE THREAD

**Issue by clarayao** [adafruit/Adafruit_CircuitPython_ServoKit#47]
Hi!
I'm currently trying to drive some servos by using `Adafruit PCA9685 16-Channel Servo Driver` and `Featherwing M4 Express`. And I am using the example code in the [Adafruit Learning System](https://learn.adafruit.com/16-channel-pwm-servo-driver?view=all#controlling-servos-2998560). However, although I ran the exact same code (with some changes to the I2C address because the PCA9685 board I'm using had been modified), I still get the error 
`Traceback (most recent call last):  
File "code.py", line 21, in <module> 
File "adafruit_servokit.py", line 88, in _ _init_ _  
ValueError: SCL in use`

And this is the code:
`import board`
`import busio`
`import time`
`import adafruit_pca9685`
`i2c = busio.I2C(board.SCL, board.SDA)`
`from adafruit_servokit import ServoKit`
`kit = ServoKit(channels=16)`
`kit.servo[0].angle = 180`
`kit.continuous_servo[1].throttle = 1`
`time.sleep(1)`
`kit.continuous_servo[1].throttle = -1`
`time.sleep(1)`
`kit.servo[0].angle = 0`
`kit.continuous_servo[1].throttle = 0`

I wonder where I did wrong. Thank you!

![image](https://user-images.githubusercontent.com/89841521/201723781-dfd22088-73d4-492d-bc02-5a8ce1b0188e.png)

**Comment by caternuson** [comment]
This library takes care of the PCA setup internally. So you don't need explicit lines of code for that, ex:
```python
 i2c = busio.I2C(board.SCL, board.SDA)
```

See the examples in this library repo for general usage syntax, esp. in how the imports and setup are done:
https://github.com/adafruit/Adafruit_CircuitPython_ServoKit/tree/main/examples
