### ISSUE TITLE
Servos don't travel nearly close to 180 degrees

### ISSUE THREAD

**Issue by scprotz** [adafruit/Adafruit_CircuitPython_ServoKit#48]
I'm a bit new to CircuitPython, but when testing the servos (a few different brands) and the PCA9685, I change the angle about 90 degrees (from say 45 to 135), but it won't traverse the full 90 degrees.  In practice I have to send about 120 degree change to the servo to get about 90 degrees of real-world rotation. (so if I want it to go from 0 to 90,  I have to send 120).

Any ideas on why this is happening?  Is there some way I can calibrate it or get closer to the full rotation of the servo?

**Comment by CedarGroveStudios** [comment]
Servo calibration varies somewhat between servo types, brands, and models; the default settings in CircuitPython will produce slightly different results. A good reference for how to use and calibrate servos in CircuitPython can be found in the excellent _Using Servos with CircuitPython_ learning guide, https://learn.adafruit.com/circuitpython-essentials/circuitpython-servo

The information about adjusting the calibration span can be found at the bottom of the referenced page.

**Comment by caternuson** [comment]
Closing. This is not a library issue. See info linked above.
